- Code_Of_Conduct.md
closes #4 
This PR addresses the addition of code of conduct markdown file to your repo. The file has been modified to meet the usage guidelines of the MCA alumni network and email ID of the author has been added for reporting purposes. Thank you. Please review and action accordingly.
> #Ads  Code_Of_Conduct.md

- .github/workflows/greetings.yml
closes #5 
This is a PR addressed to the addition of a bot that greets new users when a new PR or issue is raised.
Thank you! Please review and share the feedback.
Note : Please add level1 and GSSoC24-Ext labels to the PR please.
> #Add Create greetings.yml

- client/src/App.jsx
Scroll bar added successfully : #13 done successfully,
https://github.com/user-attachments/assets/60c31e56-8fce-4db8-9a64-cd5ed4246781
you can change scroll bar colour by just changing color value (i think light grey color will suit perfectly but you need any other color than tell me or just change color in app.jsx file(img below)
> scroll bar added : #13 done as it was assigned to me

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/components/AdminDashboard.jsx
- client/src/components/Header.jsx
#14     
Added Responsive Admin Dashboard with side bar(large screen) and bottom navbar(big screen).
> Added Admin Dashboard page

- client/src/App.jsx
- client/src/components/Header.jsx
- client/src/components/Login.jsx
- client/src/components/Register.jsx
- client/src/middleware/AuthContext.jsx
- client/src/middleware/ProtectedRoute.jsx
- client/src/utils/apiUtils.jsx
- server/controllers/user.controllers.js
- server/server.js
https://github.com/user-attachments/assets/11baaa7c-5ae2-4761-838a-4b742fde6bbb
#10 Added JWT Auth now user can register , login and logout.
Add following global variables in .env file 
URL = your_mongo_key
SECRET_KEY = your_secret_key
> Added Register and Login functionality

- client/src/components/Login.jsx
- server/server.js
#32 
Improved the login form UI
> Improve the login form UI (Neumorphism style)

- server/package.json
- server/routes/user.routes.js
Fixes [https://github.com/abhishekraoas/MCA-Alumni-Network/security/code-scanning/22](https://github.com/abhishekraoas/MCA-Alumni-Network/security/code-scanning/22)
To fix the problem, we will introduce a rate-limiting middleware using the `express-rate-limit` package. This middleware will limit the number of requests that can be made to the `handleUserSignUp` endpoint within a specified time window. We will set a reasonable limit to balance between legitimate usage and protection against abuse.
1. Install the `express-rate-limit` package.
2. Import the `express-rate-limit` package in the `server/routes/user.routes.js` file.
3. Configure the rate limiter with appropriate settings (e.g., maximum 100 requests per 15 minutes).
4. Apply the rate limiter to the `handleUserSignUp` route. …
> Fix code scanning alert no. 22: Missing rate limiting

- .env.example
Hey  i have add the files as  per the issue mention in #54
> Fixed #54 Added .env.example file

- server/.gitignore
Hey @abhishekraoas 
Hey I have modified the .gitingore file to production level and fixes #57
> Fixes #issue57 Inappropriate .gitignore Files

- server/controllers/user.controllers.js
- server/logger.js
- server/package-lock.json
- server/package.json
- server/server.js
Hey as you can see now details have been logged in continuously for every api we hit . Fixes #60
> Fixes #60 Added Logger Using Winston For Backend Service For Testing

- server/Dockerfile
Hey As you can see the docker file is running successfully , now user can run the docker file smoothly without any issue and fixes #58
> Dockerfile Updated Fixes #58

- client/package-lock.json
- client/package.json
- client/src/components/Home.jsx
- client/src/components/ImageWithCursorEffect.jsx
- server/controllers/user.controllers.js
- server/package-lock.json
- server/package.json
https://github.com/user-attachments/assets/d862b319-c0d2-4e2f-9734-5b7e0861b73b
Kindly merge this under label of #hacktoberfest-accepted and #gssoc-ext and level
THankyou ! @abhishekraoas
> This is fix for issue #118 cursor effect

- client/src/components/Home.jsx
hey there i have solved the problem you can have a look on it :)   issue number : #144
> Social media icons problem fixed 

- client/src/components/About.jsx
- client/src/components/Home.jsx
I have fix the Issue: #31 
1. Befor About-Us page layout.
2. After Modification and redesigning About-US page.
I have re- design About Us page by using Material UI to deliver a clean, responsive layout with enhanced user experience. Framer Motion was integrated to add dynamic hover effects and smooth animations, creating an interactive and engaging design. A fixed header ensures seamless navigation, allowing users to easily explore different sections of the page. This combination of technologies results in a polished and intuitive About Us page, improving both aesthetics and usability.
@abhishekraoas As our discussion and your suggestion in  #120 
I have redesign the about us page with black background
> Re-Design About Us page with modern ui features

- client/package-lock.json
- client/src/components/Register.jsx
I've fixed the broken image with original source image. I hope to  merge it with the relevant tags.
> fixed the broken image in register section

- client/src/components/Header.jsx
@abhishekraoas  @agarwalhimanshugaya I just updated the focused nav link when the user clicks on a particular section. Please check it.
GSSoc's 2024 EXTD
issue #217 done
https://github.com/user-attachments/assets/45aaab99-c306-47da-9223-41199b5e2d52
> Focused navlink in navbar

- client/src/components/Header.jsx
- client/src/components/OurAlumni.jsx
- client/src/components/Search.jsx
- client/src/components/SocialMedia.jsx
- client/src/components/UserCards.jsx
This PR introduces two major enhancements to the alumni section:
1. **Search Component**
- Implemented a search component that allows filtering by **Name**, **Skills**, **Batch**, and **City**. This provides users with a more refined search experience.
2. **User Card Design**
- Revamped the alumni card with a modern aesthetic, improving the overall look and feel of the alumni profiles.
- **Search Component**
- Added filter options for **Name**, **Skills**, **Batch**, and **City** to enhance user search capabilities.
- **User Card**
- Updated the layout and styling of the alumni card to align with contemporary design trends, ensuring a visually appealing presentation of alumni information.
1. Pull the latest changes to your local branch.
2. Start the development server and navigate to the …
> Revamped Alumni Search and User Card Design

- client/package-lock.json
- client/src/components/Register.jsx
Fixed #236 
@abhishekraoas  I have resolved the bug . Please check it out . Also I have changed padding to make the inputs Bigger. 
Please check the difference : 
Previous :
Current: 
Also I would like to work on an issue with high complexity , I am good at full stack development.
> Fixed #236,  Resolved the select button bug

- client/src/components/Contact.jsx
I have made the required modifications 
Fixed #202 
If you like it, kindly upgrade my level, I would really appreciate
> UI Enhanced of ContactUs Page

- .github/workflows/pr-checker.yaml
**FIX** #232 
**Usage:**
1. When a pull request is created or edited, the workflow automatically triggers.
2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`FIX #<issue-number>` or `FEAT, or DOC #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.
**_Note_**: Kindly add all the labels added to the issue, to this PR!
@abhishekraoas
> Implement PR Issue Checker Workflow

- client/src/App.jsx
- client/src/components/ForgotPassword.jsx
- client/src/components/InputField.jsx
- client/src/components/Login.jsx
Description
This pull request adds the Password Recovery feature, enabling users to reset their passwords through an easy-to-follow flow. It currently simulates OTP sending and verification using alerts, providing a foundation for future backend integration.
Related Issue
Fixes #241 
Changes Made
Implemented Password Recovery Component in React.js.
Developed a 3-step flow:
Email input to simulate OTP sending.
OTP verification step.
Password reset functionality.
Utilized alerts to simulate OTP actions and reset completion.
Structured the code for smooth integration with backend APIs later.
Screenshots:
https://github.com/user-attachments/assets/f69f43fe-9fb0-4852-b828-d57627a76e2a
This feature lays the groundwork for enhanced password recovery. Once a backend is available, real OTP …
> Added-Password-Recovery-feature #241

- client/src/components/Contact.jsx
- client/src/components/Footer.jsx
- client/src/components/style.css
Added hover effect on follow us icons  
issue #262 completed.
> Added hover effect on follow us icons

- client/src/components/Header.jsx
Navbar sticky issue solved, Now the navbar is sticky on the website
issue number #305 is solved
> Navbar sticky issue solved, issue number #305 is solved

- client/src/components/About.jsx
- client/src/components/Footer.jsx
- client/src/components/Home.jsx
- client/src/components/ImageWithCursorEffect.jsx
- client/src/components/OurAlumni.jsx
Reverts abhishekraoas/MCA-Alumni-Network#306
> Revert "Responsive-device"
